title: Cognos Solution
tagline: "Cognos Solution, a Jekyll blog powered by Chirpy"
description: "Tech, data, and AI projects by Ian"
url: "https://cognossolution.com"
baseurl: ""

remote_theme: cotes2020/jekyll-theme-chirpy

lang: en
timezone: America/Chicago

author:
  name: Ian Deuberry
  bio: "Tech + finance brain. I build automation, data pipelines, and AI prototypes that actually work."
  github: Sir-Ian

github:
  username: Sir-Ian

twitter:
  username: ""

social:
  name: Ian Deuberry
  email: ""
  links:
    - https://github.com/Sir-Ian

google_analytics:
  id: ""

theme_mode: "auto"

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-paginate
