title: Cognos Solution LLC
description: Projects by Ian.
url: https://cognossolution.com
baseurl: ""

theme: minima

# Basic site options
locale: en-US
markdown: kramdown
permalink: /:categories/:title/

# Author profile
author: Ian Deuberry

minima:
  social_links:
    github: Sir-Ian
    linkedin: an-deuberry

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
