title: "Cognos Solution LLC"
tagline: "Cognos Solution, a Jekyll blog"
description: "Tech, data, and AI projects."
url: "https://cognossolution.com"
baseurl: ""

theme: minima

lang: en
timezone: America/Chicago

author:
  name: "Ian M. D"
  bio: "Tech & finance background. I build automation, data pipelines, prototypes, and apps to solve problems."
  github: "Sir-Ian"

github:
  username: "Sir-Ian"


social:
  name: "Ian M. D"
  email: "ian@cognossolution.com"
  links:
    - https://github.com/Sir-Ian

google_analytics:
  id: ""

theme_mode: "auto"

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
