title: Cognos Solution
description: Tech, data, and AI projects by Ian.
url: https://cognossolution.com
baseurl: ""

theme: minima

# Basic site options
locale: en-US
markdown: kramdown
permalink: /:categories/:title/

# Author profile
author:
  name: Ian Deuberry
  avatar: /assets/images/avatar.jpg
  bio: >
    Building automation, data pipelines, prototypes, and more to solve problems and deliver value (usually).
    ENTJ/ENTP energy, consulting background, and a not-so-subtle obsession with cars.
  location: Chicago, IL
  links:
    - label: GitHub
      icon: "fab fa-github"
      url: https://github.com/YOUR_GH_USERNAME
    - label: LinkedIn
      icon: "fab fa-linkedin"
      url: https://www.linkedin.com/in/YOUR_LINKEDIN
    - label: Resume
      icon: "fas fa-file"
      url: /resume/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Navigation
header_pages:
  - index.md
  - _pages/projects.md
  - blog.md
  - _pages/contact.md
